# 第一周 Pytorch中张量应用

### 根据传入的参数，自动指定类型

In [1]:
# 可以通过传入的数据，自动判断类型
import numpy as np
import torch
# 自动推断数据类型
i = torch.tensor(1)
print(i,i.dtype) # tensor(1) torch.int64
x = torch.tensor(2.0)
print(x,x.dtype) # tensor(2.) torch.float32
b = torch.tensor(True)
print(b,b.dtype) # tensor(True) torch.bool

tensor(1) torch.int64
tensor(2.) torch.float32
tensor(True) torch.bool


### 指定张量的类型

In [2]:
# 指定数据类型
i = torch.tensor(1,dtype = torch.int32)
print(i,i.dtype) # tensor(1, dtype=torch.int32) torch.int32
x = torch.tensor(2.0,dtype = torch.double)
print(x,x.dtype) # tensor(2., dtype=torch.float64) torch.float64

tensor(1, dtype=torch.int32) torch.int32
tensor(2., dtype=torch.float64) torch.float64


### 使用特定类型的构造函数

In [3]:
i = torch.IntTensor(1)
print(i,i.dtype) # tensor([5], dtype=torch.int32) torch.int32
x = torch.Tensor(np.array(2.0))
print(x,x.dtype) #等价于torch.FloatTensor
b = torch.BoolTensor(np.array([1,0,2,0]))
print(b,b.dtype) # tensor([ True, False, True, False]) torch.bool

tensor([0], dtype=torch.int32) torch.int32
tensor(2.) torch.float32
tensor([ True, False,  True, False]) torch.bool


### 不同类型进行转换

In [4]:
i = torch.tensor(1)
print(i,i.dtype) # tensor(1) torch.int64
x = i.float()
print(x,x.dtype) #调用 float方法转换成浮点类型 tensor(1.) torch.float32
y = i.type(torch.float)
print(y,y.dtype) #使用type函数转换成浮点类型 tensor(1.) torch.float32
z = i.type_as(x)
print(z,z.dtype) #使用type_as方法转换成某个Tensor相同类型 tensor(1.) torch.float32

tensor(1) torch.int64
tensor(1.) torch.float32
tensor(1.) torch.float32
tensor(1.) torch.float32


### 张量的创建

In [6]:
x = torch.empty(5,3)
print(x)
x = torch.rand(5,3) ## 平均分布
print(x)
x = torch.randn(5,3) ## 标准正态分布
print(x)
x = torch.zeros(5,3,dtype=torch.long)
print(x)
x = torch.ones(5,3) ## 全部都是1 , 构建一个5行3列的矩阵
print(x)

tensor([[3.1346e-25, 1.6675e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.6892, 0.5280, 0.7956],
        [0.0280, 0.9468, 0.9334],
        [0.3546, 0.8401, 0.1601],
        [0.8537, 0.9223, 0.6289],
        [0.8740, 0.6019, 0.4353]])
tensor([[ 0.5404, -0.5044,  1.2821],
        [-0.2776,  0.6237,  1.0507],
        [ 0.2717,  0.2378,  0.9839],
        [-1.4353, -0.6900,  0.2245],
        [ 0.1849, -0.6874,  0.2157]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


###  4维张量

In [7]:
tensor4 = torch.tensor([[[[1.0,1.0],[2.0,2.0]],[[3.0,3.0],[4.0,4.0]]],
[[[5.0,5.0],[6.0,6.0]],[[7.0,7.0],[8.0,8.0]]]]) # 4维张量
print(tensor4)
print(tensor4.dim())

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]]],


        [[[5., 5.],
          [6., 6.]],

         [[7., 7.],
          [8., 8.]]]])
4


### 张量的三个属性
*  阶（rank）：维度. tensor.dim()
* 尺寸/形状（shape）： 行和列的数目. tensor.shape/tensor.size()
* 类型（type）： 元素的数据类型. tensor.type()

###  使用view改变张量尺寸

In [8]:
vector = torch.arange(0,12)
print(vector) # tensor([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print(vector.shape) #torch.Size([12])
matrix34 = vector.view(3,4)
print(matrix34)
print(matrix34.shape) # torch.Size([3, 4])
matrix43 = vector.view(4,-1) #-1表示该位置长度由程序自动推断
print(matrix43)
print(matrix43.shape) # torch.Size([4, 3])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([4, 3])


### 使用reshape改变张量尺寸
* 有些操作会让张量存储结构扭曲，直接使用view会失败，可以用reshape方法

In [9]:
matrix26 = torch.arange(0,12).view(2,6)
print(matrix26)
# tensor([[ 0, 1, 2, 3, 4, 5],
# [ 6, 7, 8, 9, 10, 11]])
print(matrix26.shape) #torch.Size([2, 6])
# 转置操作让张量存储结构扭曲,变成不连续的
matrix62 = matrix26.t()
print(matrix62.is_contiguous())
# 直接使用view方法会失败，可以使用reshape方法
#matrix34 = matrix62.view(3,4) #error!
matrix34 = matrix62.reshape(3,4) #等价于matrix34 = matrix62.contiguous().view(3,4)
print(matrix34)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
False
tensor([[ 0,  6,  1,  7],
        [ 2,  8,  3,  9],
        [ 4, 10,  5, 11]])


## 张量的基本运算

In [11]:
# 将对应元素相加
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x+y)
print(torch.add(x,y))
result = torch.empty(5,3)
torch.add(x,y,out=result)
y.add_(x)
print(y)
# x中的每个元素都加上2
x = torch.ones(2,2)
y = x+2
print(y)
# 对应元素相乘
x = torch.ones(2,2)
y = torch.ones(2,2)
z = x*y
print(z)

tensor([[1.3079, 1.1704, 1.3633],
        [0.4727, 1.3586, 1.6653],
        [1.3894, 0.2370, 1.0784],
        [1.0565, 1.4052, 1.4497],
        [1.3595, 1.0925, 1.2889]])
tensor([[1.3079, 1.1704, 1.3633],
        [0.4727, 1.3586, 1.6653],
        [1.3894, 0.2370, 1.0784],
        [1.0565, 1.4052, 1.4497],
        [1.3595, 1.0925, 1.2889]])
tensor([[1.3079, 1.1704, 1.3633],
        [0.4727, 1.3586, 1.6653],
        [1.3894, 0.2370, 1.0784],
        [1.0565, 1.4052, 1.4497],
        [1.3595, 1.0925, 1.2889]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[1., 1.],
        [1., 1.]])


### 张量的高级运算

In [12]:
x = torch.randn(5,3)
y = x.mean()
print(y.item())
# 计算x中所有元素的均值，然后打印均值

-0.04938589408993721


In [13]:
x = torch.rand(5,3)
print(x.sum())
# 计算得到总和

tensor(6.4355)


In [16]:
# @是用来对tensor进行矩阵相乘的：
import torch
d = 2
n=50
X = torch.randn(n,d)
true_w = torch.tensor([[-1.0],[2.0]])
y = X @ true_w + torch.randn(n,1)*0.1
print(X.shape)
print(y.shape)
print(true_w.shape)

torch.Size([50, 2])
torch.Size([50, 1])
torch.Size([2, 1])


#### 两个张量对应元素相乘，在PyTorch中可以通过torch.mul函数（或*运算符）实现；

In [17]:
# *用来对tensor进行矩阵进行逐元素相乘：
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[2,1],[4,3]])
c = x*y
print("x_shape",x.shape)
print("y_shape",y.shape)
print("c_shape",c.shape)
print(c)

x_shape torch.Size([2, 2])
y_shape torch.Size([2, 2])
c_shape torch.Size([2, 2])
tensor([[ 2,  2],
        [12, 12]])


#### 两个张量矩阵相乘，在PyTorch中可以通过torch.matmul函数实现

In [19]:
d=torch.matmul(x, y)
print(d)

tensor([[10,  7],
        [22, 15]])


### Tensor与Numpy的互相转换操作
#### numpy => Tensor

In [20]:
#torch.from_numpy函数从numpy数组得到Tensor
arr = np.zeros(3)
tensor = torch.from_numpy(arr)
print("before add 1:")
print(arr)
print(tensor)
print("\nafter add 1:")
np.add(arr,1, out = arr) #给 arr增加1，tensor也随之改变
print(arr)
print(tensor)

before add 1:
[0. 0. 0.]
tensor([0., 0., 0.], dtype=torch.float64)

after add 1:
[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


#### Tensor=>numpy

In [21]:
# numpy方法从Tensor得到numpy数组
tensor = torch.zeros(3)
arr = tensor.numpy()
print("before add 1:")
print(tensor)
print(arr)
print("\nafter add 1:")
#使用带下划线的方法表示计算结果会返回给调用 张量
tensor.add_(1) #给 tensor增加1，arr也随之改变
#或： torch.add(tensor,1,out = tensor)
print(tensor)
print(arr)
# before add 1:
# tensor([0., 0., 0.])
# [0. 0. 0.]

before add 1:
tensor([0., 0., 0.])
[0. 0. 0.]

after add 1:
tensor([1., 1., 1.])
[1. 1. 1.]


### Tensor 的降维和增维操作
Tensor关于维度的操作有很多，比如降维（torch.squeeze( )）和
增维（torch.unsqueeze( )），张量拼接（torch.cat( )）、张量扩
大（torch.Tensor.expand( )）、张量缩小（torch.Tensor.narrow( )）
等等。

####  Tensor 的裁剪操作
* clamp(x, min, max)
* 对Tensor中的元素进行范围过滤，不符合条件的可以
把它变换到范围内部（边界）上，常用于梯度裁剪
（gradient clipping），即在发生梯度离散或者梯度
爆炸时对梯度的处理。
* x是一个Tensor，min、max是两个标量，
* 如果x<min，返回min；
* 如果min<x<max，返回x；
* 如果x>max，返回max。

In [24]:
# view/reshape参数为负数指不定长度，以真实数据长度补齐
x = torch.ones(4, 4)
y = x.view(-1)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [27]:
x = torch.rand(5, 3)
y = torch.rand(3, 5)
d = torch.matmul(x, y)
print(d)

tensor([[0.3045, 0.3318, 0.7618, 0.4054, 0.8656],
        [0.3469, 0.4011, 0.8867, 0.4568, 0.9732],
        [0.4805, 0.5896, 1.2033, 0.6159, 1.4944],
        [0.1208, 0.1581, 0.3228, 0.1549, 0.3317],
        [0.3588, 0.4178, 0.9025, 0.4689, 1.0591]])


In [28]:
# 指数运算
x = torch.tensor([1.0, 2.0, 3.0])
ex = torch.exp(x)
print(x)

# 对数运算
log_x = torch.log(x)
print(log_x)

tensor([1., 2., 3.])
tensor([0.0000, 0.6931, 1.0986])
